#!/bin/sh
rm -r app-build/*

traceur --symbols=true --arrow-functions=true --unicode-expressions=true --numeric-literals=parse --unicode-escape-sequences=true --block-binding=parse --generators=parse --default-parameters=true --for-of=true --rest-parameters=true --spread=true --destructuring=true --classes=parse --computed-property-names=true --dir app app-build --modules=commonjs --source-maps
mv *.map app-build
#--source-maps
#browserify browser/braceEditor.js > browser-build/app.js--nodejs
node-debug --nodejs --harmony_typeof --nodejs --harmony_scoping --nodejs --harmony_modules  --nodejs --harmony_proxies  --nodejs --harmony_collections --nodejs --harmony_generators --nodejs --harmony_iteration  --nodejs --harmony_numeric_literals  --nodejs --harmony_strings --nodejs --harmony_arrays  --nodejs --harmony_maths  --nodejs --harmony_promises index.js

#
#node  --harmony --harmony-proxies index.js
