#!/bin/sh
rm -r app-build/*

traceur --symbols=parse --arrow-functions=true --unicode-expressions=true --numeric-literals=parse --unicode-escape-sequences=true --block-binding=parse --generators=parse --default-parameters=true --for-of=true --rest-parameters=true --spread=true --destructuring=true --classes=parse --computed-property-names=true --dir app app-build --modules=commonjs
#--source-maps
#browserify browser/braceEditor.js > browser-build/app.js
#iojs --harmony_proxies --harmony --harmony_sloppy --harmony_arrow_functions index.js | bunyan -l info
node --harmony --harmony_proxies index.js | bunyan -l debug

#
#node  --harmony --harmony-proxies index.js
